### ISSUE TITLE
TypeError: Logger\TelegramHandler::formatText(): Return value must be of type string, Illuminate\View\View returned

### ISSUE THREAD

**Issue by alex-demin** [grkamil/laravel-telegram-logging#24]
Looks like the return type of formatText() should be changed from string to Illuminate\View\View

**Comment by tsyrya** [comment]
I have the smaae issue. 
It's been here for almost a year and no one wants to fix that? is the library still being supported?

**Comment by grkamil** [comment]
I will check.

**Comment by tsyrya** [comment]
@grkamil I am so sorry, I didn't notice that the problem was actually in my config. In my case there was an error connected to redis extension, but for some reason in the console I saw the message that formatText returns the wrong type. Not, then I fixed the redis issue, the problem is gone and your code works fine.

**Comment by grkamil** [comment]
Okay, good.
